package cy.jdkdigital.productivemetalworks.datagen;

import cy.jdkdigital.productivemetalworks.ProductiveMetalworks;
import cy.jdkdigital.productivemetalworks.registry.MetalworksRegistrator;
import cy.jdkdigital.productivemetalworks.registry.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.TagsProvider;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.BlockTagCopyingItemTagProvider;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class ItemTagProvider extends BlockTagCopyingItemTagProvider
{
    public ItemTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> future, CompletableFuture<TagsProvider.TagLookup<Block>> provider) {
        super(output, future, provider, ProductiveMetalworks.MODID);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        copy(ModTags.Blocks.FOUNDRY_CONTROLLERS, ModTags.Items.FOUNDRY_CONTROLLERS);
        copy(ModTags.Blocks.FOUNDRY_DRAINS, ModTags.Items.FOUNDRY_DRAINS);
        copy(ModTags.Blocks.FOUNDRY_TANKS, ModTags.Items.FOUNDRY_TANKS);
        copy(ModTags.Blocks.FOUNDRY_CAPACITORS, ModTags.Items.FOUNDRY_CAPACITORS);
        copy(ModTags.Blocks.FOUNDRY_WINDOWS, ModTags.Items.FOUNDRY_WINDOWS);
        copy(ModTags.Blocks.FIRE_BRICKS, ModTags.Items.FIRE_BRICKS);

        tag(ModTags.Items.CASTS).add(
                MetalworksRegistrator.CAST_INGOT.get(),
                MetalworksRegistrator.CAST_NUGGET.get(),
                MetalworksRegistrator.CAST_GEM.get(),
                MetalworksRegistrator.CAST_GEAR.get(),
                MetalworksRegistrator.CAST_ROD.get(),
                MetalworksRegistrator.CAST_PLATE.get()
        );

        for (DyeColor color : DyeColor.values()) {
            tag(color.getDyedTag()).add(MetalworksRegistrator.FOUNDRY_CONTROLLERS.get(color).get().asItem());
        }

        tag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "nuggets")))
                .addTag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "nuggets/meat")));
        tag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "ingots")))
                .addTag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "ingots/meat")))
                .addTag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "ingots/shiny_meat")));
        tag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "nuggets/meat"))).add(MetalworksRegistrator.MEAT_NUGGET.get());
        tag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "ingots/meat"))).add(MetalworksRegistrator.MEAT_INGOT.get());
        tag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "ingots/shiny_meat"))).add(MetalworksRegistrator.SHINY_MEAT_INGOT.get());

        meltableTags();
    }

    // Items that have a foundry melting recipe, split into subtags. The parent productivemetalworks:meltable
    // pulls in every subtag plus anything that doesn't belong to one. Convention tags are added as optional so
    // metals/gems from mods that aren't present don't trip "undefined tag" errors.
    private void meltableTags() {
        // Metals: mirror the per-metal melting forms generated by RecipeProvider#metalCompat.
        var metals = tag(ModTags.Items.MELTABLE_METALS);
        LinkedHashSet<String> metalNames = new LinkedHashSet<>();
        for (String[] arr : List.of(RecipeProvider.PM_METALS, RecipeProvider.ATO_METALS, RecipeProvider.FTB_METALS, RecipeProvider.MI_METALS)) {
            for (String entry : arr) {
                metalNames.add(entry.substring(entry.indexOf(':') + 1));
            }
        }
        for (String name : metalNames) {
            for (String form : new String[]{"storage_blocks/", "storage_blocks/raw_", "ores/", "ingots/", "nuggets/", "raw_materials/", "dusts/", "gears/", "rods/", "plates/"}) {
                metals.addOptionalTag(ItemTags.create(Identifier.fromNamespaceAndPath("c", form + name)));
            }
        }
        metals.add(Items.ANCIENT_DEBRIS, Items.NETHERITE_SCRAP, Items.IRON_BARS, Items.IRON_DOOR, Items.IRON_TRAPDOOR,
                Items.IRON_HORSE_ARMOR, Items.GOLDEN_HORSE_ARMOR, Items.LIGHTNING_ROD, Items.CLOCK, Items.COMPASS, Items.HEAVY_CORE);

        var gems = tag(ModTags.Items.MELTABLE_GEMS);
        gems.addOptionalTags(Tags.Items.GEMS_DIAMOND, Tags.Items.ORES_DIAMOND, Tags.Items.STORAGE_BLOCKS_DIAMOND);
        gems.addOptionalTags(Tags.Items.GEMS_EMERALD, Tags.Items.ORES_EMERALD, Tags.Items.STORAGE_BLOCKS_EMERALD);
        gems.addOptionalTags(Tags.Items.GEMS_LAPIS, Tags.Items.ORES_LAPIS, Tags.Items.STORAGE_BLOCKS_LAPIS);
        gems.addOptionalTags(Tags.Items.GEMS_AMETHYST, Tags.Items.GEMS_QUARTZ, Tags.Items.ORES_QUARTZ);
        gems.addOptionalTag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "dusts/diamond")));
        gems.addOptionalTag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "dusts/quartz")));
        gems.add(Items.DIAMOND_HORSE_ARMOR, Items.AMETHYST_BLOCK, Items.QUARTZ_BLOCK, Items.QUARTZ_BRICKS, Items.QUARTZ_PILLAR);

        var organic = tag(ModTags.Items.MELTABLE_ORGANIC);
        organic.addOptionalTags(Tags.Items.FOODS_RAW_MEAT, ModTags.Items.MEAT_INGOTS, ModTags.Items.MEAT_NUGGETS, ModTags.Items.WAXES, ModTags.Items.STORAGE_BLOCK_WAXES);
        organic.add(Items.HONEYCOMB, Items.HONEYCOMB_BLOCK, Items.HONEY_BLOCK);

        // Parent: all subtags + the uncategorized meltables.
        var meltable = tag(ModTags.Items.MELTABLE);
        meltable.addTags(ModTags.Items.MELTABLE_METALS, ModTags.Items.MELTABLE_GEMS, ModTags.Items.MELTABLE_ORGANIC);
        meltable.addOptionalTags(Tags.Items.DUSTS_REDSTONE, Tags.Items.ORES_REDSTONE, Tags.Items.STORAGE_BLOCKS_REDSTONE, Tags.Items.DUSTS_GLOWSTONE);
        meltable.addOptionalTags(ItemTags.COALS, Tags.Items.ORES_COAL, Tags.Items.STORAGE_BLOCKS_COAL, ModTags.Items.STORAGE_BLOCKS_CHARCOAL);
        meltable.addOptionalTags(Tags.Items.GLASS_BLOCKS_CHEAP, Tags.Items.GLASS_PANES, Tags.Items.SANDS, Tags.Items.OBSIDIANS, Tags.Items.ENDER_PEARLS, Tags.Items.SHULKER_BOXES);
        meltable.addOptionalTag(ItemTags.create(Identifier.fromNamespaceAndPath("c", "dusts/obsidian")));
        meltable.add(Items.GLOWSTONE, Items.ENDER_EYE, Items.POPPED_CHORUS_FRUIT, Items.BLAZE_POWDER, Items.BLAZE_ROD,
                Items.SLIME_BALL, Items.SLIME_BLOCK, Items.MAGMA_BLOCK, Items.MAGMA_CREAM, Items.SHULKER_SHELL);
    }

    @Override
    public String getName() {
        return "Productive Metalworks Item Tags Provider";
    }
}
